django_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"
urlpatterns = [
    path('', views.index, name='index'),
    path('products', views.ProductList.as_view(), name='product-all-list'), #product_all/ = /shop/product_all/
    path('products/search', views.ProductList.as_view(), name='product-search'),   #detailView
    path('products/<uuid:pk>', views.ProductDetail.as_view(), name='product-detail'),   #detailView
    ##############################
    #create form
    path('products/create', views.ProductCreate.as_view(), name='product-create'),   #createView
    path('products/update/<uuid:pk>', views.ProductUpdate.as_view(), name='product-update'),   #updateView
    ####################
    #ajax
    path('products/delete', views.ProductDeleteAjax, name='product-delete'),   #detailView

]

polls/models.py
from django.db import models

# Create your models here.
# Model = table
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')
    
    def __str__(self):
        return self.question_text
    
    #TODO, can custom many model

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

shop/models.py
from django.db import models
import uuid

# Create your models here.
class Type(models.Model):
    name = models.CharField(max_length=30, unique=True, null=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30, null=False, help_text='Enter product name')
    description = models.CharField(max_length=300, help_text='Enter description')
    type = models.ForeignKey(Type, null=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_date = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name', '-update_date']

    def __str__(self):
        return f'{self.name} {self.description} {self.type} {self.update_date}'

shop/forms.py
from django import forms
from .models import Product, Type


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'type'
        ]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
            }),
        }

    # remove the help text
    def __init__(self, *args, **kwargs):
        super(ProductCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['name', 'description', 'type']:
            self.fields[fieldname].help_text = None


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'description',
        ]
        widgets = {
            'description': forms.Textarea(attrs={
            }),
        }

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse('Hello')

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView, 
    DetailView, 
    CreateView,
    UpdateView,
    DeleteView
)
from django.urls import reverse, reverse_lazy
from django.utils.timezone import now
from django.http import HttpResponse, JsonResponse

from .models import Type, Product
from .forms import ProductCreateForm, ProductUpdateForm

# Create your views here.
# View = for normal view page = controller


def index(request):
    num_product = Product.objects.all().count()
    context = {
        'name': 0
    }
    return render(request, 'index.html', context=context)


#################################
#just view
class ProductList(ListView):
    model = Product
    context_object_name = 'product_list'    # default object_list
    template_name = 'products/product_all_list_template.html'   # using template
    queryset = Product.objects.all()
    
    def get_queryset(self):
        query = self.request.GET.get('name')
        if query:
            qs = self.model.objects.filter(name__icontains=query)
            return qs
        else:
            return super().get_queryset()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('name')
        if query:
            context["title"] = "Search: " + query
        else:
            context["title"] = "All Product"
        return context
    
    

# DetailView will auto select by XX, XX = set by urls.py
#https://zhuanlan.zhihu.com/p/36989981
class ProductDetail(DetailView):
    template_name = 'products/product_detail.html'
    context_object_name = 'product'
    queryset = Product.objects.all().prefetch_related('type')

    def get_object(self, queryset=None):
        context = super(ProductDetail, self).get_object(queryset=queryset)
        # if obj.user != obj.photoextended.user:
        #     raise Http404()
        return context

##############################
#Form

class ProductCreate(CreateView):
    model = Product
    template_name = 'products/product_create.html'
    form_class = ProductCreateForm
    #success_url = reverse_lazy('shop:product-detail/{pk}')

    def form_valid(self, form):
        # for the form post is success, then do below action
        form.cleaned_data   #clean all input data
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('shop:product-detail', args=(self.object.pk,))  #args need ','  otherwise error


class ProductUpdate(UpdateView):
    model = Product
    template_name = 'products/product_update.html'
    form_class = ProductUpdateForm

    def form_valid(self, form):
        # for the form post is success, then do below action
        form.cleaned_data   #clean all input data
        form.instance.update_date = now()   #update product update_date in here
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('shop:product-detail', args=(self.object.pk,))  #args need ','  otherwise error


################################
#Ajax


#for the js ajax delete
def ProductDeleteAjax(request):
    id = request.POST.get('id', None)
    Product.objects.all().filter(id=id).delete()
    payload = {'delete': 'ok'}
    return JsonResponse(payload)

shop/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Shop</title>{% endblock %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
        integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"
        integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous">
    </script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <!-- import css -->
    <link href="{% static "base/css/style.css" %}" rel="stylesheet" type="text/css" />

    <script src="{% static "base/js/csrftoken.js" %}"></script>

    {% block js %}
    <!-- js script-->
    {% endblock %}
</head>

<body>
    {% block sidebar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{% url 'shop:index' %}">Shop</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action={% url 'shop:product-search' %}>{% csrf_token %}
                <input name="name" class="form-control mr-sm-2" type="search" placeholder="Search Product"
                    aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% endblock %}
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

shop/templates/index.html
{% extends "base/base.html" %}

{% load static %}

{% block content %}
This is index
<br />
<div class="pl-3 row">
    <a href={% url 'shop:product-all-list' %}>Product List</a>  ||
    <form method="get" action={% url 'shop:product-all-list' %}>{% csrf_token %}
        <input type='submit' text="List" />
    </form>
</div>
<br />
<a href={% url 'shop:product-create' %}>Product Create</a>
<br />



{% endblock %}

shop/templates/products/product_all_list_template.html
{% extends "base/base.html" %}
{% load static %}

{% block js %}
<script>
    function Ajax_Delete(obj) {
        $.ajax({
            url: "{% url 'shop:product-delete' %}",
            type: 'POST',
            headers: {
                'X-CSRFToken': csrftoken
            },
            mode: 'same-origin',
            datatype: 'json',
            data: {
                'id': $(obj).attr('arg')
            },
            success: function (arg) {
                location.reload()
            }
        });
    }
</script>
{% endblock %}

{% block content %}
<h1>
    {{ title }}
</h1>
{% for product in product_list %}
<div class="row">
    <a href="{% url 'shop:product-detail' product.id %}">
        Name: {{ product.name }}
        Type: {{ product.type }}
    </a>
    <form method="post">{% csrf_token %}
        <input type="button" onclick="Ajax_Delete(this);" value="Delete" arg="{{ product.id }}" />
    </form>
</div>
{% empty %}
<p>There are no Product</p>
{% endfor %}
{% endblock %}

shop/templates/products/product_create.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
    {% comment %}  
        form.as_p = auto create form with <p>, as_table = with <table> .....
        form.name =  use the create input nmae="name",  the attr e.g. class, will set in forms.py
    {% endcomment %}
    {{ form.as_p }}
    {% comment %} {{ form.name }} {% endcomment %}
    {% comment %} {{ form.description }} {% endcomment %}

    <input type="submit" value="Submit" />
</form>
{% endblock %}

shop/templates/products/product_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
{{ product.id }}
{{ product.name }}
{{ product.description }}
{{ product.create_date }}
{{ product.update_date }}
{{ product.type }}

<a href={% url 'shop:product-update' product.id %}>Product Update</a>

{% endblock %}

shop/templates/products/product_update.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<form method="post">{% csrf_token %}
    {% comment %}  
        form.as_p = auto create form with <p>, as_table = with <table> .....
        form.name =  use the create input nmae="name",  the attr e.g. class, will set in forms.py
    {% endcomment %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}